name: starter
services:
  mysql:
    image: mysql:8.0
    container_name: starter_mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    ports:
      - "9306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init/:/docker-entrypoint-initdb.d/

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: starter_adminer
    restart: unless-stopped
    ports:
      - "9080:8080"
    depends_on:
      mysql:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: starter_redis
    restart: unless-stopped
    ports:
      - "9379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redisinsight:
    image: redis/redisinsight:latest
    container_name: starter_redisinsight
    restart: unless-stopped
    ports:
      - "9540:5540"
    depends_on:
      redis:
        condition: service_healthy

volumes:
  mysql_data:
  redis_data:

networks:
  default:
    name: starter_network
