name: starter
services:
  mysql:
    image: mysql:8.0
    container_name: starter_mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "9306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - starter_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: starter_adminer
    restart: unless-stopped
    ports:
      - "9080:8080"
    networks:
      - starter_network
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:


networks:
  starter_network:
    external: true
