name: starter
services:
  redis:
    image: redis:7-alpine
    container_name: starter_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - starter_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redisinsight:
    image: redis/redisinsight:latest
    container_name: starter_redisinsight
    restart: unless-stopped
    ports:
      - "5540:5540"
    networks:
      - starter_network
    depends_on:
      redis:
        condition: "service_healthy"

volumes:
  redis_data:


networks:
  starter_network:
    external: true
