"""fix_relation between role, user, and oauth account

Revision ID: df3bb7485a96
Revises: e49c05aa3887
Create Date: 2026-04-28 10:53:16.954058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df3bb7485a96'
down_revision: Union[str, None] = 'e49c05aa3887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
